version: "3"
# name volumes: must delete manually
volumes:
  mongodb_data:
    external: false
# top level netowrks
# external false means outside of docker container can not access this network
networks:
  cocoannotator:
    external: false

services:
  frontend:
    container_name: annotator_client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "9999:8080"
    volumes:
      - "./client:/workspace/client"
    networks:
      - cocoannotator
    depends_on:
      - webserver
  webserver:
    container_name: annotator_webserver
    # image: cocoannotatorwebserver
    build:
      context: .
      dockerfile: ./backend/webserver/Dockerfile
    ports:
      - 7897:5000
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./backend/usecase:/workspace/usecase"
      - "./backend/sharedFolder:/worksapce/sharedFolder"
      - "/Users/koushiken/Desktop/ATWEX:/worksapce/sharedFolder/ATWEX"
      - "./datasets:/datasets"
      - "./models:/models"
    environment:
      - FILE_WATCHER=true
      - FLASK_APP=webserver
      - FLASK_ENV=development
      - DEBUG=true
      - PYTHONUNBUFFERED = 0

      # - MASK_RCNN_FILE=/models/mask_rcnn_coco.h5
      # # Default coco classes (order matters)
      # - |
      #   MASK_RCNN_CLASSES=
      #   BG,person,bicycle,car,motorcycle,airplane,
      #   bus,train,truck,boat,traffic light,
      #   fire hydrant,stop sign,parking meter,bench,bird,
      #   cat,dog,horse,sheep,cow,elephant,bear,
      #   zebra,giraffe,backpack,umbrella,handbag,tie,
      #   suitcase,frisbee,skis,snowboard,sports ball,
      #   kite,baseball bat,baseball glove,skateboard,
      #   surfboard,tennis racket,bottle,wine glass,cup,
      #   fork,knife,spoon,bowl,banana',apple,
      #   sandwich,orange,broccoli,carrot,hot dog,pizza,
      #   donut,cake,chair,couch,potted plant,bed,
      #   dining table,toilet,tv,laptop,mouse,remote,
      #   keyboard,cell phone,microwave,oven,toaster,
      #   sink,refrigerator,book,clock,vase,scissors,
      #   teddy bear,hair drier,toothbrush
    networks:
      - cocoannotator
    depends_on:
      - database
      - workers
  workers:
    container_name: annotator_workers
    # image: webworkers:latest
    build:
      context: .
      dockerfile: ./backend/workers/Dockerfile
    volumes:
      - "./backend/config:/workspace/config"
      - "./backend/webserver:/workspace/webserver"
      - "./backend/workers:/workspace/workers"
      - "./backend/database:/workspace/database"
      - "./datasets:/datasets"
    depends_on:
      - messageq
      - database
    ports:
      - 6666:5555
    networks:
      - cocoannotator
  database:
    image: mongo:4.0
    container_name: annotator_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "33333:27017"
    command: "mongod --smallfiles --logpath=/dev/null"
    networks:
      - cocoannotator
  messageq:
    image: rabbitmq:3
    container_name: annotator_message_q
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
    networks:
      - cocoannotator
